
import { Lunch } from "@/components/common/types";

export const LunchType = [
    {
        name: "RANDOM",
        color: " #ee7c01",
        width: "43%",
        href: "/lunch/random",
        type: "normal",
        isBounce: true
    },
    {
        name: "JAPANESE",
        color: "#c766e7",
        width: "48%",
        href: "/lunch/japanese",
        type: "normal",
    },
    {
        name: "ASIAN",
        color: "#5390f2",
        width: "31%",
        href: "/lunch/asian",
        type: "svg",
    },
    {
        name: "🍔",
        color: "#f6c101",
        width: "20%",
        href: "/lunch/burger",
        type: "normal",
    },
    {
        name: "CHINESE",
        color: "#f6c101",
        width: "35%",
        href: "/lunch/chinese",
        type: "normal",
    },
    {
        name: "ALL",
        color: "#c165e5",
        width: "47%",
        href: "/lunch/LunchList",
        type: "normal",
        hasAnimation: true
    },
    {
        name: "+",
        color: " #568EFF",
        width: "42%",
        href: "/AddLunch",
        type: "normal",
    },
    {
        name: "🥪",
        color: "#c21",
        width: "18%",
        href: "/lunch/sandwich",
        type: "normal",
    },
    {
        name: "KOREAN",
        color: "#0253c2",
        width: "38%",
        href: "/lunch/korean",
        type: "normal",
    },
    {
        name: "ITALIAN",
        color: "#117237",
        width: "28%",
        href: "/lunch/italian",
        type: "normal",
    },
    {
        name: "☕️ & 🥐",
        color: "#a60",
        width: "42%",
        href: "/lunch/coffee",
        type: "normal",
    },
    { name: "?", color: "#047462", width: "18%", href: "/about", type: "normal" },
    {
        name: "💬",
        color: "#c766e7",
        width: "18%",
        href: "/chat",
        type: "normal",
    },
];

export const DefaultTarget: Lunch = {
    name: '',
    type: '',
    description: '',
    sort: '',
    menu: '',
    url: '',
    priceRate: '',
    imageUrl: '',
    isDisplayed: false
}
export const RegisterOptions = {
    name: { required: "식당 이름을 입력해주세요.." },
    type: { required: "카테고리를 선택해주세요.." },
    description: { required: "가게 설명을 입력해주세요.." },
    sort: { required: "종류를 입력해주세요.." },
    menu: { required: "메뉴를 입력해주세요.." },
};
export const Feelings = [
    "퇴근하고 싶은",
    "설레는",
    "즐거운",
    "졸린",
    "배고픈",
    "집에가고 싶은",
    "굶주린",
    "원기옥을 모으는",
    "떵마려운",
    "텅-장 주인",
    "플렉스",
    "노래부르는",
    "춤추는",
    "인생 최대의",
    "해맑은",
    "꿈꾸는",
];

export const Foods = [
    "도나스🍩",
    "라면🍜",
    "새우튀김🍤",
    "크롸상🥐",
    "베이컨🥓",
    "쌀밥🍚",
    "국밥🍲",
    "팬케이크🥞",
    "파프리카🫑",
    "치즈🧀",
    "커퓌 ☕️",
    "피자🍕",
    "만두🥟",
    "초밥🍣",
    "통조림🥫",
    "스파게티🍝",
    "샐러드🥗",
    "초코레또🍫",
    "스파게티🍝",
    "김치찌개🍲",
    "된찌🥘",
    "우대갈비🍖",
    "스테이크🥩",
    "닭다리🍗",
    "사과🍎",
    "귤🍊",
    "딸기🍓",
    "아보카도🥑",
    "바나나🍌",
    "보리꼬리🥦",
    "옥수수🌽",
    "닭가슴살🐓",
    "햄버거🍔",
    "고구마🍠",
    "얼음🧊",
    "우유🍼",
    "맥주🍺",
    "와인🍷",
    "칵테일🍸",
    "위스키🥃",
    "칰힌🐔",
    "떡볶이🍢",
    "타코🌮",
    "케잌🍰",
    "김밥🍙",
];